### ISSUE TITLE
[Suggestion] Directory permissions after rename

### ISSUE THREAD

**Issue by chippoman** [Laharah/deluge-FileBotTool#26]
If FileBotTool creates a new folder, at least on my system, it creates them with a mask of 770 (rwxrwx---). As a result, my Plex instance couldn't see any of the new files because it couldn't access them.

As a suggestion, maybe you could implement an option window that would allow a user to specify the value that would be used to chmod the newly created directory.

For now, I worked around this issue by making my plex user part of the group it needs to to be able to parse the files.

**Comment by Laharah** [comment]
The permissions are determined by deluge. When filebottool calls filebot, filebot is opened as a child process of deluge, which inherits deluge's [umask](https://en.wikipedia.org/wiki/Umask). If you want new files to have a different umask than what the system default is, you'll have to launch deluge/deluged daemon with it.

If you run the deluge server as a background service, you can set it in the systemd config file. Here's an example with a umask of 002, which should have rw permissions for user and group and readonly for everyone else:

```
#/etc/systemd/system/deluged.service
[Unit]
Description=Deluge Bittorrent Client Daemon
After=network-online.target

[Service]
Type=simple
User=deluge
Group=deluge
UMask=002

ExecStart=/usr/local/bin/deluged -d

Restart=on-failure

# Configures the time to wait before service is stopped forcefully.
TimeoutStopSec=300

[Install]
WantedBy=multi-user.target
```

If you're using systemd or upstart, you'll have to look up how to set the umask since I don't remember how off the top of my head.

**Comment by Laharah** [comment]
I'm gonna close this for now as solved, but if you're still running into problems, feel free to re-open.
