### ISSUE TITLE
Seeding location changed in deluge

### ISSUE THREAD

**Issue by niayh** [Laharah/deluge-FileBotTool#3]
Hi there,

Love the plugin and what you've done with it -- excellent addition to Deluge and very nice interface to make dealing with filebot easier.

I have a request when it comes to renaming files. The tool renames the file and moves/hardlinks/symlinks whatever to the specified location -- however at the same time it also changes the seeding location and torrent name in Deluge. Is there a way to add an option so that seeding torrents are not disturbed in Deluge and the file is simply hardlinked isntead? For the sake of my organization I like to keep my torrent clients and library folder separate. This makes things much easier in the even that I move servers

**Comment by Laharah** [comment]
Well, if you move servers, but keep using deluge, you can move your deluge data folder to keep everything seeding. 

I've considered making it so that only the "move" rename action affects seeding locations, but the problem I see with it is that there would be no feedback for the user. There would be no way to tell which torrents had been sorted, and which torrents hadn't.

I've also considered just removing all actions except move and copy, since as you point out, it doesn't really serve a purpose to redirect the seeding location to file links. The only reason they're currently in is that FileBot supports them.

I know that sonarr/sickbeard support what you're looking for, which is kind of a point on the side of removing links completely.

I'll think about it a bit more now that you've given me a concrete use-case. If you've got any ideas on how to provide link feedback to the user, I'd be happy to entertain them.

**Comment by niayh** [comment]
Problem is when I move servers, I prefer to recreate all the hardlinks using filebot at time of move -- my library never gets moved and is considered volatile and rebuildable. These files wouldn't necessarily get lost in a server move under my current workflow; however, they just wouldn't get re-seeded

I do use sickrage to manage my TV shows -- however, I'm not a huge fan of couchpotato (though I do have it integrated with Plex Requests on my server).

Personally, I think link feedback can easily be found by viewing the "Filebot History" for each particular torrent. Further feedback is provided to me when the file actually appears in my Plex library ;)

Perhaps for further feedback, you could add a column to the UI which indicates whether or not an item has been processed by the plugin?

**Comment by Laharah** [comment]
Well, thinking it over, I may prevent seeding from sym/hardlinks by default, and add a message showing the new links on completion of a right-click manual rename.

As much as I'd like to put in another column for better feedback,  it'd require either some sort of database for my plugin, or adding extra data to every torrent added, which seems invasive, and has a lot of overhead with maintaining state. 

I could also add a logfile people can check to show errors with auto-renames. It won't be ideal, but it's a start. I'll see about implementing the changes over the weekend.

**Comment by Laharah** [comment]
Implemented that new functionality you were looking for. You can test it out with the new release:

https://github.com/Laharah/deluge-FileBotTool/releases/tag/0.9.0

Haven't implemented a logfile I like yet, so you still can't get info about new links created by auto-sort rules, but beta 0.9 should get your setup working. Let me know if you run into issues with it.

**Comment by niayh** [comment]
Thanks for the update! I'll give it a shot and let you know how it's working in a day or so.

**Comment by niayh** [comment]
I had to reboot deluge entirely (I missed your edit until just now), but it is functioning perfectly now! Thanks so much for the feature, it is greatly appreciated. Will certainly be recommending this plugin to others
