### ISSUE TITLE
FileBot not found issue in Ubuntu 16.04

### ISSUE THREAD

**Issue by jkanczler** [Laharah/deluge-FileBotTool#34]
When deploying FileBot from Ubuntu's software center then FileBot is installed into to /snap/bin folder. Therefore the plugin is incorrectly trying to start it from /usr/bin folder.

Workaround:
Create a symlink between /usr/bin/flexget and /snap/bin/flexget.

**Comment by rednoah** [comment]
Either way, `filebot` will be in the `$PATH` so FileBot should be called by calling `filebot`.

**Comment by Laharah** [comment]
were you getting a "filebot not found" warning when you tried to rename a torrent? It should have been where the filebot version information is up at the top. The program should have defaulted to using just `filebot` and relying on the path if it doesn't find it in the expected locations. 

When the plugin starts it makes a `filebot.exe -version` call. Since filebot wasn't in `/usr/bin` or `/usr/local/bin` it should have defaulted to just `filebot -version` and let the path variable find the executable. If it wasn't finding filebot at all and you were getting the filebot not found error, either the user deluge was running on didn't have `/snap/bin/filebot` in it's path, something was wrong with permissions, or the path cache was stale.

Either way I'll add `/snap/bin/filebot` (I'm assuming that's what you meant to say) to the locations where the plugin searches for a filebot executable.

**Comment by jkanczler** [comment]
Yeah. I meant that. I'm talking about Linux, Ubuntu version 16.04. I installed filebot from Ubuntu software:
![image](https://user-images.githubusercontent.com/10925650/28845026-f634014a-7706-11e7-80c1-b5c6af067700.png)

The executable is installed at:
![image](https://user-images.githubusercontent.com/10925650/28845110-3ca9cc9a-7707-11e7-8f5c-a38e6b765081.png)

**Comment by Laharah** [comment]
I've added `/snap/bin/filebot` to the list of locations the plugin explicitly checks for filebot. Hopefully that will help people out who have stale path caches.

**Comment by jkanczler** [comment]
Just to verify that it works in 1.1.10:

1. I deleted the symlink from the /usr/bin folder and the FileBot tool 1.1.9 started to complain about FileBot is not found.
2. I've installed 1.10, FileBot tool could find FileBot at /snap/bin location. Thanks for the fix.
