### ISSUE TITLE
Not Overwriting?

### ISSUE THREAD

**Issue by jmansell90** [Laharah/deluge-FileBotTool#6]
So on many (if not almost all) torrents you have the classic text files advertising the people that made it.  Well, in the renaming and moving process, nothing I do will make it overwrite or skip that file.  I've tried all the "On Conflict" settings, it refuses to continue.

**Comment by Laharah** [comment]
I'm not quite sure I understand what you mean. Are you doing a standard rename, or are you trying to link the files, or something else?

Right now, any files that aren't renamed by filebot (which would include the extra text files) are moved to the same folder where the files are relocated to. Are you trying to remove those files?

**Comment by jmansell90** [comment]
I'm trying to do a rename and move.  Say I have TVShow.S01E02.avi, TVShow.S01E02.nfo, and TEAMTORRENT.COM.txt as the files downloaded.  I run the FileBotTool to scrape the data from TVDB, rename the file with expression "{n}\Season {s}\{sxe} - {t}", and move it to E:\TV (Where there is already a TVShow.S01E01.avi, TVShow.S01E01.nfo, and TEAMTORRENT.COM.txt.  "On Conflict" can be set to either skip or override, either way I will be presented with an error that it could not copy TEAMTORRENT.COM.txt because it already exists in the folder.

**Comment by Laharah** [comment]
ahhh, I see. For now you'll have to delete the non-media files (assuming they're not the same files you're seeding) and then do the rename.

Right now, duplicate files that aren't renamed by filebot will prevent the rename from going forward. I think I will change it so that when `override` is on it applies to all files, including ones not touched by filebot.

**Comment by Laharah** [comment]
I've updated the plugin to fix this: fbcf957b, and I added some UI to warn the user about data loss when using override conflict resolution since files can be overwritten.

test out the new build here: https://github.com/Laharah/deluge-FileBotTool/releases/tag/0.9.5

I'm gonna close this, but feel free to re-open if it's not behaving as you expect.
